BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'clear'
        on_release: app.clear_all()
    TextInput:
        id: input_name
        text: ''
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
        id: output_label
    Label:
        text: 'Enter your name'
    Button:
        color: (1, 1, 0, 1)
        text: 'Hello Guido'